// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.4
// source: auxiliary.proto

package auxiliary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a BROADCAST message sent during Round 1 of the EDDSA TSS keygen protocol.
type AuxRound1Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *AuxRound1Message) Reset() {
	*x = AuxRound1Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auxiliary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuxRound1Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxRound1Message) ProtoMessage() {}

func (x *AuxRound1Message) ProtoReflect() protoreflect.Message {
	mi := &file_auxiliary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxRound1Message.ProtoReflect.Descriptor instead.
func (*AuxRound1Message) Descriptor() ([]byte, []int) {
	return file_auxiliary_proto_rawDescGZIP(), []int{0}
}

func (x *AuxRound1Message) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Represents a BROADCAST message sent to each party during Round 2 of the EDDSA TSS keygen protocol.
type AuxRound2Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ssid      []byte `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Srid      []byte `protobuf:"bytes,2,opt,name=srid,proto3" json:"srid,omitempty"`
	PaillierN []byte `protobuf:"bytes,3,opt,name=paillier_n,json=paillierN,proto3" json:"paillier_n,omitempty"`
	PedersenS []byte `protobuf:"bytes,4,opt,name=pedersen_s,json=pedersenS,proto3" json:"pedersen_s,omitempty"`
	PedersenT []byte `protobuf:"bytes,5,opt,name=pedersen_t,json=pedersenT,proto3" json:"pedersen_t,omitempty"`
	PrmProof  []byte `protobuf:"bytes,6,opt,name=prm_proof,json=prmProof,proto3" json:"prm_proof,omitempty"`
	Rho       []byte `protobuf:"bytes,7,opt,name=rho,proto3" json:"rho,omitempty"`
	U         []byte `protobuf:"bytes,8,opt,name=u,proto3" json:"u,omitempty"`
}

func (x *AuxRound2Message) Reset() {
	*x = AuxRound2Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auxiliary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuxRound2Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxRound2Message) ProtoMessage() {}

func (x *AuxRound2Message) ProtoReflect() protoreflect.Message {
	mi := &file_auxiliary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxRound2Message.ProtoReflect.Descriptor instead.
func (*AuxRound2Message) Descriptor() ([]byte, []int) {
	return file_auxiliary_proto_rawDescGZIP(), []int{1}
}

func (x *AuxRound2Message) GetSsid() []byte {
	if x != nil {
		return x.Ssid
	}
	return nil
}

func (x *AuxRound2Message) GetSrid() []byte {
	if x != nil {
		return x.Srid
	}
	return nil
}

func (x *AuxRound2Message) GetPaillierN() []byte {
	if x != nil {
		return x.PaillierN
	}
	return nil
}

func (x *AuxRound2Message) GetPedersenS() []byte {
	if x != nil {
		return x.PedersenS
	}
	return nil
}

func (x *AuxRound2Message) GetPedersenT() []byte {
	if x != nil {
		return x.PedersenT
	}
	return nil
}

func (x *AuxRound2Message) GetPrmProof() []byte {
	if x != nil {
		return x.PrmProof
	}
	return nil
}

func (x *AuxRound2Message) GetRho() []byte {
	if x != nil {
		return x.Rho
	}
	return nil
}

func (x *AuxRound2Message) GetU() []byte {
	if x != nil {
		return x.U
	}
	return nil
}

// Represents a P2P message sent during Round 3 of the TSS keygen protocol.
type AuxRound3Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FacProof []byte `protobuf:"bytes,1,opt,name=fac_proof,json=facProof,proto3" json:"fac_proof,omitempty"`
	ModProof []byte `protobuf:"bytes,2,opt,name=mod_proof,json=modProof,proto3" json:"mod_proof,omitempty"`
}

func (x *AuxRound3Message) Reset() {
	*x = AuxRound3Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auxiliary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuxRound3Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxRound3Message) ProtoMessage() {}

func (x *AuxRound3Message) ProtoReflect() protoreflect.Message {
	mi := &file_auxiliary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxRound3Message.ProtoReflect.Descriptor instead.
func (*AuxRound3Message) Descriptor() ([]byte, []int) {
	return file_auxiliary_proto_rawDescGZIP(), []int{2}
}

func (x *AuxRound3Message) GetFacProof() []byte {
	if x != nil {
		return x.FacProof
	}
	return nil
}

func (x *AuxRound3Message) GetModProof() []byte {
	if x != nil {
		return x.ModProof
	}
	return nil
}

var File_auxiliary_proto protoreflect.FileDescriptor

var file_auxiliary_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x75, 0x78, 0x69, 0x6c, 0x69, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x16, 0x74, 0x73, 0x73, 0x6c, 0x69, 0x62, 0x2e, 0x63, 0x67, 0x67, 0x6d, 0x70, 0x2e,
	0x61, 0x75, 0x78, 0x69, 0x6c, 0x69, 0x61, 0x72, 0x79, 0x22, 0x26, 0x0a, 0x10, 0x41, 0x75, 0x78,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x22, 0xd4, 0x01, 0x0a, 0x10, 0x41, 0x75, 0x78, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x73, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x72,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x72, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x61, 0x69, 0x6c, 0x6c, 0x69, 0x65, 0x72, 0x5f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x70, 0x61, 0x69, 0x6c, 0x6c, 0x69, 0x65, 0x72, 0x4e, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x65, 0x64, 0x65, 0x72, 0x73, 0x65, 0x6e, 0x5f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x70, 0x65, 0x64, 0x65, 0x72, 0x73, 0x65, 0x6e, 0x53, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x65, 0x64, 0x65, 0x72, 0x73, 0x65, 0x6e, 0x5f, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x70, 0x65, 0x64, 0x65, 0x72, 0x73, 0x65, 0x6e, 0x54, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x72, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x70, 0x72, 0x6d, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x68, 0x6f, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x68, 0x6f, 0x12, 0x0c, 0x0a, 0x01, 0x75, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x75, 0x22, 0x4c, 0x0a, 0x10, 0x41, 0x75, 0x78, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x33, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x61, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x66, 0x61, 0x63, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64,
	0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x6f,
	0x64, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42, 0x11, 0x5a, 0x0f, 0x63, 0x67, 0x67, 0x6d, 0x70, 0x2f,
	0x61, 0x75, 0x78, 0x69, 0x6c, 0x69, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_auxiliary_proto_rawDescOnce sync.Once
	file_auxiliary_proto_rawDescData = file_auxiliary_proto_rawDesc
)

func file_auxiliary_proto_rawDescGZIP() []byte {
	file_auxiliary_proto_rawDescOnce.Do(func() {
		file_auxiliary_proto_rawDescData = protoimpl.X.CompressGZIP(file_auxiliary_proto_rawDescData)
	})
	return file_auxiliary_proto_rawDescData
}

var file_auxiliary_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auxiliary_proto_goTypes = []interface{}{
	(*AuxRound1Message)(nil), // 0: tsslib.cggmp.auxiliary.AuxRound1Message
	(*AuxRound2Message)(nil), // 1: tsslib.cggmp.auxiliary.AuxRound2Message
	(*AuxRound3Message)(nil), // 2: tsslib.cggmp.auxiliary.AuxRound3Message
}
var file_auxiliary_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auxiliary_proto_init() }
func file_auxiliary_proto_init() {
	if File_auxiliary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auxiliary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuxRound1Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auxiliary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuxRound2Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auxiliary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuxRound3Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auxiliary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auxiliary_proto_goTypes,
		DependencyIndexes: file_auxiliary_proto_depIdxs,
		MessageInfos:      file_auxiliary_proto_msgTypes,
	}.Build()
	File_auxiliary_proto = out.File
	file_auxiliary_proto_rawDesc = nil
	file_auxiliary_proto_goTypes = nil
	file_auxiliary_proto_depIdxs = nil
}
