// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.4
// source: aff_msg.proto

package affproof

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaillierAffAndGroupRangeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Salt []byte `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	S    []byte `protobuf:"bytes,2,opt,name=S,proto3" json:"S,omitempty"`
	T    []byte `protobuf:"bytes,3,opt,name=T,proto3" json:"T,omitempty"`
	A    []byte `protobuf:"bytes,4,opt,name=A,proto3" json:"A,omitempty"`
	Bx   []byte `protobuf:"bytes,5,opt,name=Bx,proto3" json:"Bx,omitempty"`
	By   []byte `protobuf:"bytes,6,opt,name=By,proto3" json:"By,omitempty"`
	E    []byte `protobuf:"bytes,7,opt,name=E,proto3" json:"E,omitempty"`
	F    []byte `protobuf:"bytes,8,opt,name=F,proto3" json:"F,omitempty"`
	Z1   string `protobuf:"bytes,9,opt,name=z1,proto3" json:"z1,omitempty"`
	Z2   string `protobuf:"bytes,10,opt,name=z2,proto3" json:"z2,omitempty"`
	Z3   string `protobuf:"bytes,11,opt,name=z3,proto3" json:"z3,omitempty"`
	Z4   string `protobuf:"bytes,12,opt,name=z4,proto3" json:"z4,omitempty"`
	W    []byte `protobuf:"bytes,13,opt,name=w,proto3" json:"w,omitempty"`
	Wy   []byte `protobuf:"bytes,14,opt,name=wy,proto3" json:"wy,omitempty"`
}

func (x *PaillierAffAndGroupRangeMessage) Reset() {
	*x = PaillierAffAndGroupRangeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aff_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaillierAffAndGroupRangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaillierAffAndGroupRangeMessage) ProtoMessage() {}

func (x *PaillierAffAndGroupRangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_aff_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaillierAffAndGroupRangeMessage.ProtoReflect.Descriptor instead.
func (*PaillierAffAndGroupRangeMessage) Descriptor() ([]byte, []int) {
	return file_aff_msg_proto_rawDescGZIP(), []int{0}
}

func (x *PaillierAffAndGroupRangeMessage) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *PaillierAffAndGroupRangeMessage) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *PaillierAffAndGroupRangeMessage) GetT() []byte {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *PaillierAffAndGroupRangeMessage) GetA() []byte {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *PaillierAffAndGroupRangeMessage) GetBx() []byte {
	if x != nil {
		return x.Bx
	}
	return nil
}

func (x *PaillierAffAndGroupRangeMessage) GetBy() []byte {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *PaillierAffAndGroupRangeMessage) GetE() []byte {
	if x != nil {
		return x.E
	}
	return nil
}

func (x *PaillierAffAndGroupRangeMessage) GetF() []byte {
	if x != nil {
		return x.F
	}
	return nil
}

func (x *PaillierAffAndGroupRangeMessage) GetZ1() string {
	if x != nil {
		return x.Z1
	}
	return ""
}

func (x *PaillierAffAndGroupRangeMessage) GetZ2() string {
	if x != nil {
		return x.Z2
	}
	return ""
}

func (x *PaillierAffAndGroupRangeMessage) GetZ3() string {
	if x != nil {
		return x.Z3
	}
	return ""
}

func (x *PaillierAffAndGroupRangeMessage) GetZ4() string {
	if x != nil {
		return x.Z4
	}
	return ""
}

func (x *PaillierAffAndGroupRangeMessage) GetW() []byte {
	if x != nil {
		return x.W
	}
	return nil
}

func (x *PaillierAffAndGroupRangeMessage) GetWy() []byte {
	if x != nil {
		return x.Wy
	}
	return nil
}

type PaillierOperationAndCommitmentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Salt []byte `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	S    []byte `protobuf:"bytes,2,opt,name=S,proto3" json:"S,omitempty"`
	T    []byte `protobuf:"bytes,3,opt,name=T,proto3" json:"T,omitempty"`
	A    []byte `protobuf:"bytes,4,opt,name=A,proto3" json:"A,omitempty"`
	Bx   []byte `protobuf:"bytes,5,opt,name=Bx,proto3" json:"Bx,omitempty"`
	By   []byte `protobuf:"bytes,6,opt,name=By,proto3" json:"By,omitempty"`
	E    []byte `protobuf:"bytes,7,opt,name=E,proto3" json:"E,omitempty"`
	F    []byte `protobuf:"bytes,8,opt,name=F,proto3" json:"F,omitempty"`
	Z1   string `protobuf:"bytes,9,opt,name=z1,proto3" json:"z1,omitempty"`
	Z2   string `protobuf:"bytes,10,opt,name=z2,proto3" json:"z2,omitempty"`
	Z3   string `protobuf:"bytes,11,opt,name=z3,proto3" json:"z3,omitempty"`
	Z4   string `protobuf:"bytes,12,opt,name=z4,proto3" json:"z4,omitempty"`
	W    []byte `protobuf:"bytes,13,opt,name=w,proto3" json:"w,omitempty"`
	Wx   []byte `protobuf:"bytes,14,opt,name=wx,proto3" json:"wx,omitempty"`
	Wy   []byte `protobuf:"bytes,15,opt,name=wy,proto3" json:"wy,omitempty"`
}

func (x *PaillierOperationAndCommitmentMessage) Reset() {
	*x = PaillierOperationAndCommitmentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aff_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaillierOperationAndCommitmentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaillierOperationAndCommitmentMessage) ProtoMessage() {}

func (x *PaillierOperationAndCommitmentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_aff_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaillierOperationAndCommitmentMessage.ProtoReflect.Descriptor instead.
func (*PaillierOperationAndCommitmentMessage) Descriptor() ([]byte, []int) {
	return file_aff_msg_proto_rawDescGZIP(), []int{1}
}

func (x *PaillierOperationAndCommitmentMessage) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *PaillierOperationAndCommitmentMessage) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *PaillierOperationAndCommitmentMessage) GetT() []byte {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *PaillierOperationAndCommitmentMessage) GetA() []byte {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *PaillierOperationAndCommitmentMessage) GetBx() []byte {
	if x != nil {
		return x.Bx
	}
	return nil
}

func (x *PaillierOperationAndCommitmentMessage) GetBy() []byte {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *PaillierOperationAndCommitmentMessage) GetE() []byte {
	if x != nil {
		return x.E
	}
	return nil
}

func (x *PaillierOperationAndCommitmentMessage) GetF() []byte {
	if x != nil {
		return x.F
	}
	return nil
}

func (x *PaillierOperationAndCommitmentMessage) GetZ1() string {
	if x != nil {
		return x.Z1
	}
	return ""
}

func (x *PaillierOperationAndCommitmentMessage) GetZ2() string {
	if x != nil {
		return x.Z2
	}
	return ""
}

func (x *PaillierOperationAndCommitmentMessage) GetZ3() string {
	if x != nil {
		return x.Z3
	}
	return ""
}

func (x *PaillierOperationAndCommitmentMessage) GetZ4() string {
	if x != nil {
		return x.Z4
	}
	return ""
}

func (x *PaillierOperationAndCommitmentMessage) GetW() []byte {
	if x != nil {
		return x.W
	}
	return nil
}

func (x *PaillierOperationAndCommitmentMessage) GetWx() []byte {
	if x != nil {
		return x.Wx
	}
	return nil
}

func (x *PaillierOperationAndCommitmentMessage) GetWy() []byte {
	if x != nil {
		return x.Wy
	}
	return nil
}

var File_aff_msg_proto protoreflect.FileDescriptor

var file_aff_msg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x66, 0x66, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x74, 0x73, 0x73, 0x6c, 0x69, 0x62, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x61,
	0x66, 0x66, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0xf9, 0x01, 0x0a, 0x1f, 0x50, 0x61, 0x69, 0x6c,
	0x6c, 0x69, 0x65, 0x72, 0x41, 0x66, 0x66, 0x41, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x61, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12,
	0x0c, 0x0a, 0x01, 0x53, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x53, 0x12, 0x0c, 0x0a,
	0x01, 0x54, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x54, 0x12, 0x0c, 0x0a, 0x01, 0x41,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x41, 0x12, 0x0e, 0x0a, 0x02, 0x42, 0x78, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x42, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x42, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x42, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x45, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x45, 0x12, 0x0c, 0x0a, 0x01, 0x46, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x01, 0x46, 0x12, 0x0e, 0x0a, 0x02, 0x7a, 0x31, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x7a, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x7a, 0x32, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x7a, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x7a, 0x33, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x7a, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x7a, 0x34, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x7a, 0x34, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x01, 0x77, 0x12, 0x0e, 0x0a, 0x02, 0x77, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x02, 0x77, 0x79, 0x22, 0x8f, 0x02, 0x0a, 0x25, 0x50, 0x61, 0x69, 0x6c, 0x6c, 0x69, 0x65, 0x72,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c,
	0x74, 0x12, 0x0c, 0x0a, 0x01, 0x53, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x53, 0x12,
	0x0c, 0x0a, 0x01, 0x54, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x54, 0x12, 0x0c, 0x0a,
	0x01, 0x41, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x41, 0x12, 0x0e, 0x0a, 0x02, 0x42,
	0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x42, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x42,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x42, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x45,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x45, 0x12, 0x0c, 0x0a, 0x01, 0x46, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x46, 0x12, 0x0e, 0x0a, 0x02, 0x7a, 0x31, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x7a, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x7a, 0x32, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x7a, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x7a, 0x33, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x7a, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x7a, 0x34, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x7a, 0x34, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x01, 0x77, 0x12, 0x0e, 0x0a, 0x02, 0x77, 0x78, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x77, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x77, 0x79, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x77, 0x79, 0x42, 0x11, 0x5a, 0x0f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f,
	0x61, 0x66, 0x66, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aff_msg_proto_rawDescOnce sync.Once
	file_aff_msg_proto_rawDescData = file_aff_msg_proto_rawDesc
)

func file_aff_msg_proto_rawDescGZIP() []byte {
	file_aff_msg_proto_rawDescOnce.Do(func() {
		file_aff_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_aff_msg_proto_rawDescData)
	})
	return file_aff_msg_proto_rawDescData
}

var file_aff_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aff_msg_proto_goTypes = []interface{}{
	(*PaillierAffAndGroupRangeMessage)(nil),       // 0: tsslib.crypto.affproof.PaillierAffAndGroupRangeMessage
	(*PaillierOperationAndCommitmentMessage)(nil), // 1: tsslib.crypto.affproof.PaillierOperationAndCommitmentMessage
}
var file_aff_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aff_msg_proto_init() }
func file_aff_msg_proto_init() {
	if File_aff_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aff_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaillierAffAndGroupRangeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aff_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaillierOperationAndCommitmentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aff_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aff_msg_proto_goTypes,
		DependencyIndexes: file_aff_msg_proto_depIdxs,
		MessageInfos:      file_aff_msg_proto_msgTypes,
	}.Build()
	File_aff_msg_proto = out.File
	file_aff_msg_proto_rawDesc = nil
	file_aff_msg_proto_goTypes = nil
	file_aff_msg_proto_depIdxs = nil
}
