// Copyright © 2020 AMIS Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.4
// source: message1.proto

package paillier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// https://eprint.iacr.org/2021/060.pdf
// Section 2.2
type RingPederssenParameterMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Z    [][]byte `protobuf:"bytes,1,rep,name=z,proto3" json:"z,omitempty"`
	A    [][]byte `protobuf:"bytes,2,rep,name=a,proto3" json:"a,omitempty"`
	N    []byte   `protobuf:"bytes,3,opt,name=n,proto3" json:"n,omitempty"`
	S    []byte   `protobuf:"bytes,4,opt,name=s,proto3" json:"s,omitempty"`
	T    []byte   `protobuf:"bytes,5,opt,name=t,proto3" json:"t,omitempty"`
	Salt []byte   `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
}

func (x *RingPederssenParameterMessage) Reset() {
	*x = RingPederssenParameterMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RingPederssenParameterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingPederssenParameterMessage) ProtoMessage() {}

func (x *RingPederssenParameterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingPederssenParameterMessage.ProtoReflect.Descriptor instead.
func (*RingPederssenParameterMessage) Descriptor() ([]byte, []int) {
	return file_message1_proto_rawDescGZIP(), []int{0}
}

func (x *RingPederssenParameterMessage) GetZ() [][]byte {
	if x != nil {
		return x.Z
	}
	return nil
}

func (x *RingPederssenParameterMessage) GetA() [][]byte {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *RingPederssenParameterMessage) GetN() []byte {
	if x != nil {
		return x.N
	}
	return nil
}

func (x *RingPederssenParameterMessage) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *RingPederssenParameterMessage) GetT() []byte {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *RingPederssenParameterMessage) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type PaillierBlumMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A    [][]byte `protobuf:"bytes,1,rep,name=a,proto3" json:"a,omitempty"`
	B    [][]byte `protobuf:"bytes,2,rep,name=b,proto3" json:"b,omitempty"`
	W    []byte   `protobuf:"bytes,3,opt,name=w,proto3" json:"w,omitempty"`
	X    [][]byte `protobuf:"bytes,4,rep,name=x,proto3" json:"x,omitempty"`
	Z    [][]byte `protobuf:"bytes,5,rep,name=z,proto3" json:"z,omitempty"`
	Salt [][]byte `protobuf:"bytes,6,rep,name=salt,proto3" json:"salt,omitempty"`
}

func (x *PaillierBlumMessage) Reset() {
	*x = PaillierBlumMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaillierBlumMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaillierBlumMessage) ProtoMessage() {}

func (x *PaillierBlumMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaillierBlumMessage.ProtoReflect.Descriptor instead.
func (*PaillierBlumMessage) Descriptor() ([]byte, []int) {
	return file_message1_proto_rawDescGZIP(), []int{1}
}

func (x *PaillierBlumMessage) GetA() [][]byte {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *PaillierBlumMessage) GetB() [][]byte {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *PaillierBlumMessage) GetW() []byte {
	if x != nil {
		return x.W
	}
	return nil
}

func (x *PaillierBlumMessage) GetX() [][]byte {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *PaillierBlumMessage) GetZ() [][]byte {
	if x != nil {
		return x.Z
	}
	return nil
}

func (x *PaillierBlumMessage) GetSalt() [][]byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type EncryptRangeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Salt []byte `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	S    []byte `protobuf:"bytes,2,opt,name=S,proto3" json:"S,omitempty"`
	A    []byte `protobuf:"bytes,3,opt,name=A,proto3" json:"A,omitempty"`
	C    []byte `protobuf:"bytes,4,opt,name=C,proto3" json:"C,omitempty"`
	Z1   string `protobuf:"bytes,5,opt,name=z1,proto3" json:"z1,omitempty"`
	Z2   []byte `protobuf:"bytes,6,opt,name=z2,proto3" json:"z2,omitempty"`
	Z3   string `protobuf:"bytes,7,opt,name=z3,proto3" json:"z3,omitempty"`
}

func (x *EncryptRangeMessage) Reset() {
	*x = EncryptRangeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptRangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRangeMessage) ProtoMessage() {}

func (x *EncryptRangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRangeMessage.ProtoReflect.Descriptor instead.
func (*EncryptRangeMessage) Descriptor() ([]byte, []int) {
	return file_message1_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptRangeMessage) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *EncryptRangeMessage) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *EncryptRangeMessage) GetA() []byte {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *EncryptRangeMessage) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *EncryptRangeMessage) GetZ1() string {
	if x != nil {
		return x.Z1
	}
	return ""
}

func (x *EncryptRangeMessage) GetZ2() []byte {
	if x != nil {
		return x.Z2
	}
	return nil
}

func (x *EncryptRangeMessage) GetZ3() string {
	if x != nil {
		return x.Z3
	}
	return ""
}

var File_message1_proto protoreflect.FileDescriptor

var file_message1_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x61, 0x69, 0x6c, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x79, 0x0a, 0x1d, 0x52, 0x69,
	0x6e, 0x67, 0x50, 0x65, 0x64, 0x65, 0x72, 0x73, 0x73, 0x65, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x7a,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x01, 0x7a, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x01, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x01, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x73, 0x61, 0x6c, 0x74, 0x22, 0x6f, 0x0a, 0x13, 0x50, 0x61, 0x69, 0x6c, 0x6c, 0x69, 0x65,
	0x72, 0x42, 0x6c, 0x75, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x01,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x01, 0x77, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x01, 0x7a, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x13, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x61,
	0x6c, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x53, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x53,
	0x12, 0x0c, 0x0a, 0x01, 0x41, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x41, 0x12, 0x0c,
	0x0a, 0x01, 0x43, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x43, 0x12, 0x0e, 0x0a, 0x02,
	0x7a, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x7a, 0x31, 0x12, 0x0e, 0x0a, 0x02,
	0x7a, 0x32, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x7a, 0x32, 0x12, 0x0e, 0x0a, 0x02,
	0x7a, 0x33, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x7a, 0x33, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x74, 0x61, 0x6d,
	0x69, 0x73, 0x2f, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f,
	0x7a, 0x6b, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2f, 0x70, 0x61, 0x69, 0x6c, 0x6c, 0x69, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message1_proto_rawDescOnce sync.Once
	file_message1_proto_rawDescData = file_message1_proto_rawDesc
)

func file_message1_proto_rawDescGZIP() []byte {
	file_message1_proto_rawDescOnce.Do(func() {
		file_message1_proto_rawDescData = protoimpl.X.CompressGZIP(file_message1_proto_rawDescData)
	})
	return file_message1_proto_rawDescData
}

var file_message1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message1_proto_goTypes = []interface{}{
	(*RingPederssenParameterMessage)(nil), // 0: paillier.RingPederssenParameterMessage
	(*PaillierBlumMessage)(nil),           // 1: paillier.PaillierBlumMessage
	(*EncryptRangeMessage)(nil),           // 2: paillier.EncryptRangeMessage
}
var file_message1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message1_proto_init() }
func file_message1_proto_init() {
	if File_message1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RingPederssenParameterMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaillierBlumMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptRangeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message1_proto_goTypes,
		DependencyIndexes: file_message1_proto_depIdxs,
		MessageInfos:      file_message1_proto_msgTypes,
	}.Build()
	File_message1_proto = out.File
	file_message1_proto_rawDesc = nil
	file_message1_proto_goTypes = nil
	file_message1_proto_depIdxs = nil
}
