// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.4
// source: prm_msg.proto

package prmproof

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RingPederssenParameterMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Z    [][]byte `protobuf:"bytes,1,rep,name=z,proto3" json:"z,omitempty"`
	A    [][]byte `protobuf:"bytes,2,rep,name=a,proto3" json:"a,omitempty"`
	N    []byte   `protobuf:"bytes,3,opt,name=n,proto3" json:"n,omitempty"`
	S    []byte   `protobuf:"bytes,4,opt,name=s,proto3" json:"s,omitempty"`
	T    []byte   `protobuf:"bytes,5,opt,name=t,proto3" json:"t,omitempty"`
	Salt []byte   `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
}

func (x *RingPederssenParameterMessage) Reset() {
	*x = RingPederssenParameterMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prm_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RingPederssenParameterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingPederssenParameterMessage) ProtoMessage() {}

func (x *RingPederssenParameterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_prm_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingPederssenParameterMessage.ProtoReflect.Descriptor instead.
func (*RingPederssenParameterMessage) Descriptor() ([]byte, []int) {
	return file_prm_msg_proto_rawDescGZIP(), []int{0}
}

func (x *RingPederssenParameterMessage) GetZ() [][]byte {
	if x != nil {
		return x.Z
	}
	return nil
}

func (x *RingPederssenParameterMessage) GetA() [][]byte {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *RingPederssenParameterMessage) GetN() []byte {
	if x != nil {
		return x.N
	}
	return nil
}

func (x *RingPederssenParameterMessage) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *RingPederssenParameterMessage) GetT() []byte {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *RingPederssenParameterMessage) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

var File_prm_msg_proto protoreflect.FileDescriptor

var file_prm_msg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x72, 0x6d, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x15, 0x74, 0x73, 0x73, 0x6c, 0x69, 0x62, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x70,
	0x72, 0x6d, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x79, 0x0a, 0x1d, 0x52, 0x69, 0x6e, 0x67, 0x50, 0x65,
	0x64, 0x65, 0x72, 0x73, 0x73, 0x65, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x01, 0x7a, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01,
	0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x73, 0x12,
	0x0c, 0x0a, 0x01, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c,
	0x74, 0x42, 0x11, 0x5a, 0x0f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6d, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prm_msg_proto_rawDescOnce sync.Once
	file_prm_msg_proto_rawDescData = file_prm_msg_proto_rawDesc
)

func file_prm_msg_proto_rawDescGZIP() []byte {
	file_prm_msg_proto_rawDescOnce.Do(func() {
		file_prm_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_prm_msg_proto_rawDescData)
	})
	return file_prm_msg_proto_rawDescData
}

var file_prm_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_prm_msg_proto_goTypes = []interface{}{
	(*RingPederssenParameterMessage)(nil), // 0: tsslib.crypto.prmroof.RingPederssenParameterMessage
}
var file_prm_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prm_msg_proto_init() }
func file_prm_msg_proto_init() {
	if File_prm_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prm_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RingPederssenParameterMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prm_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prm_msg_proto_goTypes,
		DependencyIndexes: file_prm_msg_proto_depIdxs,
		MessageInfos:      file_prm_msg_proto_msgTypes,
	}.Build()
	File_prm_msg_proto = out.File
	file_prm_msg_proto_rawDesc = nil
	file_prm_msg_proto_goTypes = nil
	file_prm_msg_proto_depIdxs = nil
}
